// Made by Lereldarion (https://github.com/lereldarion/unity-shaders)
// Free to redistribute under the MIT license

// Debug view for lighting metadata by generating 3D gizmos.
// Runs on a mesh with at least one point, all gizmos are generated by geometry passes.
// See debug_lighting.hlsl for gizmo documentation.

Shader "Lereldarion/Debug/Lighting" {
    Properties {
        _Distance_Limit ("If positive, this is a threshold which disables the shader if distance(camera, object) > threshold", Float) = 10
        
        [Header(Anchor)]
        [Enum(Mesh origin, 0, Camera, 1)] _Anchor_Mode ("Anchor for lightprobe sampler and directional lights", Float) = 0
        _Anchor_ViewSpace_Displacement ("Viewspace displacement from anchor position", Vector) = (0, 0, 0, 0)
        
        [Header(Gizmos sizes)]
        _Directional_Light_Arrow_Length ("Directional light arrow length", Float) = 0.5
        _LightProbe_Radius ("Light Probe sphere radius", Float) = 0.05
        _ReflectionProbe_Radius ("Reflection Probe sphere radius", Float) = 0.2
        _Light_Radius ("Radius of light center gizmos (sphere cookie, octahedron, ...)", Float) = 0.2
        _Minimum_Gizmo_To_Range_Ratio ("Reduce gizmo radius of short-ranged lights to keep this size ratio", Range(0, 1)) = 0.5
    }
    SubShader {
        Tags {
            "Queue" = "Overlay"
            "RenderType" = "Overlay"
            "VRCFallback" = "Hidden"
            "PreviewType" = "Plane"
            "IgnoreProjector" = "True"
            "DisableBatching" = "True" // Distance limit needs object center
        }

        Pass {
            Name "Base Visible Lines"
            Tags { "LightMode" = "ForwardBase" }

            ZTest LEqual

            CGPROGRAM
            #include "debug_lighting.hlsl"
            #pragma vertex vertex_stage
            #pragma geometry geometry_lines_base
            #pragma fragment fragment_lines_visible
            #pragma multi_compile_instancing
            ENDCG
        }
        Pass {
            Name "Additive Visible Lines"
            Tags { "LightMode" = "ForwardAdd" }

            ZTest LEqual

            CGPROGRAM
            #include "debug_lighting.hlsl"
            #pragma vertex vertex_stage
            #pragma geometry geometry_lines_add
            #pragma fragment fragment_lines_visible
            #pragma multi_compile_instancing
            #pragma multi_compile_fwdadd
            ENDCG
        }
        Pass {
            Name "Base Spheres"
            Tags { "LightMode" = "ForwardBase" }

            ZTest LEqual

            CGPROGRAM
            #include "debug_lighting.hlsl"
            #pragma vertex vertex_stage
            #pragma geometry geometry_triangles_base
            #pragma fragment fragment_triangles
            #pragma multi_compile_instancing
            ENDCG
        }
        Pass {
            Name "Base Occluded Lines"
            Tags { "LightMode" = "ForwardBase" }

            ZTest Greater
            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off

            CGPROGRAM
            #include "debug_lighting.hlsl"
            #pragma vertex vertex_stage
            #pragma geometry geometry_lines_base
            #pragma fragment fragment_lines_occluded
            #pragma multi_compile_instancing
            ENDCG
        }
        Pass {
            Name "Additive Occluded Lines"
            Tags { "LightMode" = "ForwardAdd" }

            ZTest Greater
            Blend SrcAlpha OneMinusSrcAlpha
            ZWrite Off

            CGPROGRAM
            #include "debug_lighting.hlsl"
            #pragma vertex vertex_stage
            #pragma geometry geometry_lines_add
            #pragma fragment fragment_lines_occluded
            #pragma multi_compile_instancing
            #pragma multi_compile_fwdadd
            ENDCG
        }
    }
}
